version: '3'
services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: connect
      MYSQL_USER: connectservice2
      MYSQL_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: connectservice2
      PMA_PASSWORD: 123456
    ports:
      - "8081:80"
volumes:
  db_data: